#
# .zshrc is sourced in interactive shells.
# It should contain commands to set up aliases,
# functions, options, key bindings, etc.
#

echo "Loading ~/.zshrc"

autoload -U compinit
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
#setopt APPEND_HISTORY
## for sharing history between zsh processes
#setopt INC_APPEND_HISTORY
#setopt SHARE_HISTORY

## never ever beep ever
#setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
#MAILCHECK=0

# autoload -U colors
#colors

[ -f "$HOME/.config/shell/paths" ] && . "$HOME/.config/shell/paths"
export PATH

# Load aliases
ALIAS_FILE="${HOME}/.config/shell/aliases"
if [ -f "$ALIAS_FILE" ]; then
    . "$ALIAS_FILE"
fi

# Load functions
[ -f "$HOME/.config/shell/functions" ] && . "$HOME/.config/shell/functions"
